import asyncio, subprocess, sys, os, time
from playwright.async_api import async_playwright
D=os.path.abspath('dist'); MOCK=open('test/mock-supabase.js').read()
srv=subprocess.Popen([sys.executable,'-m','http.server','8765','-d',D],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL); time.sleep(1)
async def main():
  async with async_playwright() as p:
    b=await p.chromium.launch(); ctx=await b.new_context(viewport={'width':400,'height':860})
    await ctx.route('**/cdn.jsdelivr.net/**',lambda r:r.fulfill(body=MOCK,content_type='application/javascript'))
    await ctx.route('**/config.js',lambda r:r.fulfill(body='window.COCOON_CONFIG={url:"https://mock.supabase.co",key:"anon"};',content_type='application/javascript'))
    await ctx.route('**/fonts.g*/**',lambda r:r.abort())
    pg=await ctx.new_page(); errs=[]; pg.on('pageerror',lambda e:errs.append(str(e))); pg.on('console',lambda m: m.type=='error' and errs.append('console:'+m.text))
    await pg.goto('http://localhost:8765/'); await pg.wait_for_timeout(800)
    await pg.screenshot(path='../w1.png')
    await pg.click('#cxGate [data-go="signup"]'); await pg.fill('#cxGate input[name=email]','angel@test.fr'); await pg.fill('#cxGate input[name=pw]','secret123'); await pg.click('#cxGate .cx-btn')
    await pg.wait_for_timeout(500); await pg.screenshot(path='../w2.png')
    t0=time.time(); await pg.click('#cxGate [data-act="create"]'); await pg.wait_for_selector('#cxGate', state='hidden'); print('foyer créé en', round(time.time()-t0,2),'s'); await pg.wait_for_timeout(2500)
    await pg.screenshot(path='../w3.png')
    await pg.click('#spGo'); await pg.fill('#wzNom','Nours'); await pg.click('#wzNext')
    await pg.click('.opt:has-text("En couple")'); await pg.fill('#wzPart','Emma'); await pg.click('#wzNext')
    await pg.click('.opt:has-text("Pas d")'); await pg.click('#wzNext')
    await pg.click('.opt:has-text("Appartement")'); await pg.click('.opt:has-text("Locataire")'); await pg.click('#wzNext')
    await pg.click('.opt:has-text("Aucun")'); await pg.click('#wzNext'); await pg.click('.opt:has-text("Suivre les colis")'); await pg.click('#wzNext')
    await pg.click('#wzNext'); await pg.wait_for_timeout(4200)
    await pg.fill('#fiNom','Angel'); await pg.click('#fiSave'); await pg.wait_for_timeout(2600)
    await pg.click('#navAdd'); await pg.fill('#quickTitle','Arroser les plantes'); await pg.click('#quickForm button[type=submit]'); await pg.wait_for_timeout(2000)
    print('snap:', await pg.evaluate("!!localStorage.getItem('cocoon.snap')"), 'auth LS:', await pg.evaluate("!!localStorage.getItem('cocoon.auth')"))
    import time as _t
    t0=_t.time(); await pg.reload()
    await pg.wait_for_function("document.querySelector('#cxIntro')===null && !document.getElementById('boot')", timeout=15000)
    print('app prête après rechargement en', round(_t.time()-t0,2),'s ; gate visible:', await pg.evaluate("(()=>{const g=document.getElementById('cxGate'); return !!g&&!g.hidden})()"))
    await pg.click('.tab[data-tab="foyer"]'); await pg.wait_for_timeout(300)
    print('tâche présente:', await pg.locator('text=Arroser les plantes').count()>0)
    await pg.click('.tab[data-tab="moi"]'); await pg.wait_for_timeout(300)
    pg.once('dialog', lambda d: asyncio.ensure_future(d.accept()))
    await pg.click('#cxAccount [data-a="out"]'); await pg.wait_for_timeout(2500)
    print('après déconnexion gate:', await pg.evaluate("(()=>{const g=document.getElementById('cxGate'); return !!g&&!g.hidden})()"), 'snap:', await pg.evaluate("!!localStorage.getItem('cocoon.snap')"))
    await pg.screenshot(path='../kp1.png')
    print('errors',errs)
    await b.close()
try: asyncio.run(main())
finally: srv.kill()
