import asyncio, subprocess, sys, os, time
from playwright.async_api import async_playwright
D=os.path.abspath('dist'); MOCK=open('test/mock-supabase.js').read()
srv=subprocess.Popen([sys.executable,'-m','http.server','8765','-d',D],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL); time.sleep(1)
async def main():
  async with async_playwright() as p:
    b=await p.chromium.launch(); ctx=await b.new_context(viewport={'width':400,'height':860})
    await ctx.route('**/cdn.jsdelivr.net/**',lambda r:r.fulfill(body=MOCK,content_type='application/javascript'))
    await ctx.route('**/config.js',lambda r:r.fulfill(body='window.COCOON_CONFIG={url:"https://mock.supabase.co",key:"anon"};',content_type='application/javascript'))
    await ctx.route('**/fonts.g*/**',lambda r:r.abort())
    pg=await ctx.new_page(); errs=[]; pg.on('pageerror',lambda e:errs.append(str(e))); pg.on('console',lambda m: m.type=='error' and errs.append('console:'+m.text))
    await pg.add_init_script('window.__noTour=1')
    await pg.goto('http://localhost:8765/'); await pg.wait_for_timeout(800)
    await pg.screenshot(path='../w1.png')
    await pg.click('#cxGate [data-go="signup"]'); await pg.fill('#cxGate input[name=email]','angel@test.fr'); await pg.fill('#cxGate input[name=pw]','secret123'); await pg.click('#cxGate .cx-btn')
    await pg.wait_for_timeout(500); await pg.screenshot(path='../w2.png')
    t0=time.time(); await pg.click('#cxGate [data-act="create"]'); await pg.wait_for_selector('#cxGate', state='hidden'); print('foyer créé en', round(time.time()-t0,2),'s'); await pg.wait_for_timeout(2500)
    await pg.screenshot(path='../w3.png')
    await pg.click('#spGo'); await pg.fill('#wzNom','Nours'); await pg.click('#wzNext')
    await pg.click('.opt:has-text("En couple")'); await pg.fill('#wzPart','Emma'); await pg.click('#wzNext')
    await pg.click('.opt:has-text("Pas d")'); await pg.click('#wzNext')
    await pg.click('.opt:has-text("Appartement")'); await pg.click('.opt:has-text("Locataire")'); await pg.click('#wzNext')
    await pg.click('#wzNext'); await pg.click('.opt:has-text("Aucun")'); await pg.click('#wzNext')
    while not await pg.is_visible('.opt:has-text("Suivre les colis")'): await pg.click('#wzNext')
    await pg.click('.opt:has-text("Suivre les colis")'); await pg.click('#wzNext')
    await pg.click('#wzNext'); await pg.wait_for_timeout(4200)
    await pg.fill('#fiNom','Angel'); await pg.fill('#fiNaissance','1990-05-04'); await pg.click('#fiSave'); await pg.wait_for_timeout(2600)
    await pg.click('#navAdd'); await pg.fill('#quickTitle','Arroser les plantes'); await pg.click('#quickForm button[type=submit]'); await pg.wait_for_timeout(2000)
    await pg.wait_for_timeout(1200)
    F=await pg.evaluate("__mock.T.cocoon_foyers[0].id")
    await pg.click('.tab[data-tab="foyer"]'); await pg.click('.viewseg button[data-go="courses"] >> visible=true'); await pg.wait_for_timeout(200)
    await pg.fill('#cNom','lait, pain, tomates'); await pg.press('#cNom','Enter'); await pg.wait_for_timeout(500)
    # Emma part faire les courses (autre téléphone)
    await pg.evaluate("([F])=>__mock.remote({foyer:F,path:'coursesLive',id:'session',data:{par:'emma',depuis:Date.now(),fin:null},updated_by:'u-emma'})",[F]); await pg.wait_for_timeout(400)
    print('bandeau:', (await pg.inner_text('#cLive')).replace('\n',' | '))
    print('toast:', await pg.inner_text('#toast'))
    print('badge cloche:', await pg.evaluate("(document.querySelector('#bellBtn .bdg, #bellBtn [class*=badge], #bellBtn span')||{}).textContent"))
    # Emma coche le lait, et j'ajoute du beurre -> elle le voit ; elle ajoute des oeufs -> je le vois
    lait=await pg.evaluate("__mock.T.cocoon_docs.find(r=>r.path==='courses'&&r.data.nom==='Lait')")
    lait['data'].update({'fait':True,'faitPar':'emma','faitLe':0}); lait['updated_by']='u-emma'
    await pg.evaluate("r=>__mock.remote(r)",lait)
    await pg.evaluate("([F])=>__mock.remote({foyer:F,path:'courses',id:'x1',data:{nom:'Oeufs',pour:'tous',fait:false,ajoutePar:'emma',ajouteLe:Date.now()},updated_by:'u-emma'})",[F]); await pg.wait_for_timeout(500)
    print('toast2:', await pg.inner_text('#toast'))
    print('flash:', await pg.locator('.c-item.flash').count(), '| caddie avatar emma:', await pg.locator('.c-list.done .c-by').count(), '| nouveau:', await pg.locator('.c-new').count())
    await pg.add_style_tag(content='.toast{display:none!important}')
    await pg.evaluate("scrollTo(0,0)"); await pg.screenshot(path='../lv1.png',clip={'x':0,'y':0,'width':400,'height':820})
    await pg.click('.tab[data-tab="accueil"]'); await pg.wait_for_timeout(300); print('accueil:', [t for t in (await pg.inner_text('.secretary')).split('\n') if 'courses' in t])
    await pg.click('#bellBtn'); await pg.wait_for_timeout(400); print('cloche:', (await pg.inner_text('#npanel'))[:120].replace('\n',' | ')); await pg.keyboard.press('Escape'); await pg.wait_for_timeout(300)
    # Repas puis hors connexion
    await pg.click('.tab[data-tab="foyer"]'); await pg.click('.viewseg button[data-go="repas"] >> visible=true'); await pg.wait_for_timeout(200)
    await pg.evaluate("__mock.offline=true"); await ctx.set_offline(True); await pg.wait_for_timeout(200)
    await pg.locator('.r-day.r-today .r-e-soir').click(); await pg.locator('.r-ideas button:has-text("Pizza maison")').click(); await pg.locator('.r-ed button[type=submit]').click(); await pg.wait_for_timeout(300)
    print('hors ligne -> file:', await pg.evaluate("cocoonHost.pending()"), '| plat affiché:', await pg.locator('.r-p:has-text("Pizza maison")').count())
    await pg.evaluate("__mock.offline=false"); await ctx.set_offline(False); await pg.wait_for_timeout(1500)
    print('retour -> file:', await pg.evaluate("cocoonHost.pending()"), '| base repas:', await pg.evaluate("__mock.T.cocoon_docs.filter(r=>r.path==='repas').map(r=>r.data.plat)"), '| mozzarella en base:', await pg.evaluate("__mock.T.cocoon_docs.some(r=>r.path==='courses'&&r.data.nom==='Mozzarella')"))
    print('errors',[e for e in errs if 'ERR_' not in e])
    await b.close()
try: asyncio.run(main())
finally: srv.kill()
