import asyncio, subprocess, sys, os, time
from playwright.async_api import async_playwright
D=os.path.abspath('dist'); MOCK=open('test/mock-supabase.js').read()
srv=subprocess.Popen([sys.executable,'-m','http.server','8765','-d',D],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL); time.sleep(1)
async def main():
  async with async_playwright() as p:
    b=await p.chromium.launch(); ctx=await b.new_context(viewport={'width':400,'height':860})
    await ctx.route('**/cdn.jsdelivr.net/**',lambda r:r.fulfill(body=MOCK,content_type='application/javascript'))
    await ctx.route('**/config.js',lambda r:r.fulfill(body='window.COCOON_CONFIG={url:"https://mock.supabase.co",key:"anon"};',content_type='application/javascript'))
    await ctx.route('**/fonts.g*/**',lambda r:r.abort())
    pg=await ctx.new_page(); errs=[]; pg.on('pageerror',lambda e:errs.append(str(e))); pg.on('console',lambda m: m.type=='error' and errs.append('console:'+m.text))
    await pg.goto('http://localhost:8765/'); await pg.wait_for_timeout(800)
    await pg.screenshot(path='../w1.png')
    await pg.click('#cxGate [data-go="signup"]'); await pg.fill('#cxGate input[name=email]','angel@test.fr'); await pg.fill('#cxGate input[name=pw]','secret123'); await pg.click('#cxGate .cx-btn')
    await pg.wait_for_timeout(500); await pg.screenshot(path='../w2.png')
    t0=time.time(); await pg.click('#cxGate [data-act="create"]'); await pg.wait_for_selector('#cxGate', state='hidden'); print('foyer créé en', round(time.time()-t0,2),'s'); await pg.wait_for_timeout(2500)
    await pg.screenshot(path='../w3.png')
    await pg.click('#spGo'); await pg.fill('#wzNom','Nours'); await pg.click('#wzNext')
    await pg.click('.opt:has-text("En couple")'); await pg.fill('#wzPart','Emma'); await pg.click('#wzNext')
    await pg.click('.opt:has-text("Pas d")'); await pg.click('#wzNext')
    await pg.click('.opt:has-text("Appartement")'); await pg.click('.opt:has-text("Locataire")'); await pg.click('#wzNext')
    await pg.click('.opt:has-text("Aucun")'); await pg.click('#wzNext'); await pg.click('.opt:has-text("Suivre les colis")'); await pg.click('#wzNext')
    await pg.click('#wzNext'); await pg.wait_for_timeout(4200)
    await pg.fill('#fiNom','Angel'); await pg.click('#fiSave'); await pg.wait_for_timeout(2600)
    await pg.add_style_tag(content='.toast{display:none!important}')
    await pg.click('#navAdd'); await pg.fill('#quickTitle','Appeler le plombier'); await pg.click('#quickForm button[type=submit]'); await pg.wait_for_timeout(400)
    await pg.click('.tab[data-tab="foyer"]'); await pg.click('.viewseg button[data-go="documents"] >> visible=true'); await pg.wait_for_timeout(200)
    await pg.fill('#dTitle','Bail'); await pg.set_input_files('#dFile','../tst.png'); await pg.click('#dSubmit'); await pg.wait_for_timeout(600)
    print('requêtes de lecture:',await pg.evaluate("__mock.calls.filter(c=>c[0]==='select').map(c=>c[1]).join(',')"))
    n=await pg.evaluate("__mock.T.cocoon_docs.map(r=>r.path+'/'+r.id.slice(0,4)+' '+(r.data.titre||r.data.nom||''))"); print('docs en base:',len(n)); print('\n'.join(n))
    print('fichiers:',await pg.evaluate("Object.keys(__mock.files)"))
    print('lien ouvrir:',await pg.evaluate("(document.querySelector('.bd-eye')||{}).href"))
    # modif à distance (Emma)
    await pg.evaluate("""(()=>{const t=__mock.T.cocoon_docs.find(r=>r.path==='taches'&&r.data.titre==='Appeler le plombier'); const r=JSON.parse(JSON.stringify(t)); r.data.titre='Appeler le plombier (Emma)'; r.updated_by='emma'; __mock.remote(r);})()""")
    await pg.wait_for_timeout(400); await pg.click('.viewseg button[data-go="foyer"] >> visible=true'); await pg.wait_for_timeout(300)
    print('remote visible:', await pg.locator('text=Appeler le plombier (Emma)').count()>0)
    # suppression d'un papier → fichier supprimé
    await pg.click('.tab[data-tab="moi"]'); await pg.wait_for_timeout(300)
    print('compte:', (await pg.inner_text('#cxAccount')).replace('\n',' | '))
    await pg.locator('#cxAccount').scroll_into_view_if_needed(); await pg.screenshot(path='../w4.png')
    await pg.evaluate("""(()=>{ const f=__mock.T.cocoon_members[0].foyer; __mock.remote({foyer:f,path:'taches',id:'em1',data:{titre:'Faire les courses',cat:'courses',pour:'tous',fait:true,faitPar:'emma',faitLe:Date.now()-3600e3,creePar:'emma',creeLe:1},updated_by:'emma'}); __mock.remote({foyer:f,path:'mercis',id:'x_emma',data:{de:'emma',a:'angel',tache:'x',titre:'Sortir le chien',le:Date.now()-600e3},updated_by:'emma'}); })()""")
    await pg.wait_for_timeout(500)
    await pg.click('.tab[data-tab="foyer"]'); await pg.click('.viewseg button[data-go="foyer"] >> visible=true'); await pg.wait_for_timeout(300)
    await pg.click('#doneSummary'); await pg.wait_for_timeout(300)
    mb=pg.locator('#doneList .merci-b').first; print('bouton merci:', await mb.inner_text())
    await mb.click(); await pg.wait_for_timeout(600); print('merci en base:', await pg.evaluate("JSON.stringify(__mock.T.cocoon_docs.filter(r=>r.path==='mercis').map(r=>r.id+':'+r.data.de+'->'+r.data.a))"))
    await pg.locator('#doneList .item:has-text("Faire les courses")').screenshot(path='../mc1.png')
    await pg.evaluate("scrollTo(0,0)"); await pg.click('#bellBtn'); await pg.wait_for_timeout(400); await pg.screenshot(path='../mc2.png',clip={'x':0,'y':0,'width':400,'height':520})
    await pg.keyboard.press('Escape')
    print('pill:', await pg.inner_text('#cocBtn'))
    print('invite:', await pg.evaluate("cocoonHost.inviteUrl()"))
    print('errors',errs)
    await b.close()
try: asyncio.run(main())
finally: srv.kill()
