import asyncio, subprocess, sys, os, time
from playwright.async_api import async_playwright
D=os.path.abspath('dist'); MOCK=open('test/mock-supabase.js').read()
srv=subprocess.Popen([sys.executable,'-m','http.server','8765','-d',D],stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL); time.sleep(1)
async def main():
  async with async_playwright() as p:
    b=await p.chromium.launch(); ctx=await b.new_context(viewport={'width':400,'height':860})
    await ctx.route('**/cdn.jsdelivr.net/**',lambda r:r.fulfill(body=MOCK,content_type='application/javascript'))
    await ctx.route('**/config.js',lambda r:r.fulfill(body='window.COCOON_CONFIG={url:"https://mock.supabase.co",key:"anon"};',content_type='application/javascript'))
    await ctx.route('**/fonts.g*/**',lambda r:r.abort())
    pg=await ctx.new_page(); errs=[]; pg.on('pageerror',lambda e:errs.append(str(e))); pg.on('console',lambda m: m.type=='error' and errs.append('console:'+m.text))
    await pg.goto('http://localhost:8765/'); await pg.wait_for_timeout(800)
    await pg.screenshot(path='../w1.png')
    await pg.click('#cxGate [data-go="signup"]'); await pg.fill('#cxGate input[name=email]','angel@test.fr'); await pg.fill('#cxGate input[name=pw]','secret123'); await pg.click('#cxGate .cx-btn')
    await pg.wait_for_timeout(500); await pg.screenshot(path='../w2.png')
    t0=time.time(); await pg.click('#cxGate [data-act="create"]'); await pg.wait_for_selector('#cxGate', state='hidden'); print('foyer créé en', round(time.time()-t0,2),'s'); await pg.wait_for_timeout(2500)
    await pg.screenshot(path='../w3.png')
    await pg.click('#spGo'); await pg.fill('#wzNom','Nours'); await pg.click('#wzNext')
    await pg.click('.opt:has-text("En couple")'); await pg.fill('#wzPart','Emma'); await pg.click('#wzNext')
    await pg.click('.opt:has-text("Pas d")'); await pg.click('#wzNext')
    await pg.click('.opt:has-text("Appartement")'); await pg.click('.opt:has-text("Locataire")'); await pg.click('#wzNext')
    await pg.click('#wzNext'); await pg.click('.opt:has-text("Aucun")'); await pg.click('#wzNext')
    while not await pg.is_visible('.opt:has-text("Suivre les colis")'): await pg.click('#wzNext')
    await pg.click('.opt:has-text("Suivre les colis")'); await pg.click('#wzNext')
    await pg.click('#wzNext'); await pg.wait_for_timeout(4200)
    await pg.fill('#fiNom','Angel'); await pg.fill('#fiNaissance','1990-05-04'); await pg.click('#fiSave'); await pg.wait_for_timeout(2600)
    await pg.click('#navAdd'); await pg.fill('#quickTitle','Arroser les plantes'); await pg.click('#quickForm button[type=submit]'); await pg.wait_for_timeout(2000)
    await pg.wait_for_timeout(1500)
    inbase=lambda t: pg.evaluate("t=>__mock.T.cocoon_docs.some(r=>r.data&&r.data.titre===t)", t)
    async def add(t):
      await pg.click('#navAdd'); await pg.fill('#quickTitle',t); await pg.click('#quickForm button[type=submit]'); await pg.wait_for_timeout(600)
    await add('Tâche en ligne'); print('en ligne -> base:', await inbase('Tâche en ligne'))
    # 1) coupure puis retour du réseau
    await pg.evaluate("__mock.offline=true"); await ctx.set_offline(True); await pg.wait_for_timeout(300)
    await add('Tâche hors ligne 1'); await add('Tâche hors ligne 2')
    print('bandeau:', await pg.inner_text('.cx-off'), '| visible:', await pg.evaluate("document.querySelector('.cx-off').classList.contains('on')"))
    print('affichée:', await pg.locator('text=Tâche hors ligne 1').count()>0, '| en base:', await inbase('Tâche hors ligne 1'), '| file:', await pg.evaluate("cocoonHost.pending()"))
    await pg.screenshot(path='../off1.png',clip={'x':0,'y':0,'width':400,'height':300})
    await pg.evaluate("__mock.offline=false"); await ctx.set_offline(False); await pg.wait_for_timeout(700); print("toast:", await pg.inner_text(".cx-off"), await pg.evaluate("document.querySelector('.cx-off').className")); await pg.wait_for_timeout(800)
    print('retour réseau -> base:', await inbase('Tâche hors ligne 1'), await inbase('Tâche hors ligne 2'), '| file:', await pg.evaluate("cocoonHost.pending()"), '| bandeau:', await pg.inner_text('.cx-off'))
    # 2) modifs hors ligne puis fermeture de l'app : renvoyées au prochain lancement
    await pg.evaluate("__mock.offline=true"); await ctx.set_offline(True); await pg.wait_for_timeout(200)
    await add('Tâche avant fermeture'); print('file avant fermeture:', await pg.evaluate("cocoonHost.pending()"))
    await pg.wait_for_timeout(1500)
    await ctx.set_offline(False); await pg.reload()
    await pg.wait_for_function("document.querySelector('#cxIntro')===null && !document.getElementById('boot')", timeout=15000); await pg.wait_for_timeout(2500)
    print('après relance -> base:', await inbase('Tâche avant fermeture'), '| file:', await pg.evaluate("cocoonHost.pending()"), '| outbox LS:', await pg.evaluate("localStorage.getItem('cocoon.outbox')"))
    await pg.click('.tab[data-tab="foyer"]'); await pg.wait_for_timeout(300)
    print('toutes visibles:', [await pg.locator('text='+t).count()>0 for t in ['Tâche en ligne','Tâche hors ligne 1','Tâche avant fermeture']])
    print('errors',[e for e in errs if 'ERR_FAILED' not in e and 'INTERNET' not in e])
    await b.close()
try: asyncio.run(main())
finally: srv.kill()
